fr:
  inherit: base
es:
  inherit: base
ja:
  inherit: base
zh:
  inherit: base
it:
  inherit: base
base:
  links: []
  targets:
    - 'latex'
    - 'json'
    - 'singlehtml'
    - 'html'
    - 'man'
    - 'epub'
    - 'dirhtml'
  doc-root:
    - 'sitemap.xml'
    - 'osd.xml'
  branch-root: null
