import { loadContextifiedMongoDBModule } from './tools/runner/vm_context_helper';

type all = typeof import('./mongodb');
let exportSource: all;
try {
  exportSource = loadContextifiedMongoDBModule() as all;
} catch (error) {
  throw new Error(
    `Failed to load contextified MongoDB module: ${error instanceof Error ? error.message : String(error)}`
  );
}

// Export public API from the contextified module
// Hint: This list isn't automatically alphabetized, but VSCode's "Sort Lines Ascending" command can be used to keep it organized
export const {
  abortable,
  applySession,
  AUTH_MECHS_AUTH_SRC_EXTERNAL,
  AuthMechanism,
  aws4Sign,
  BufferPool,
  ChangeStreamCursor,
  checkParentDomainMatch,
  ClientSession,
  Collection,
  COMMAND_FAILED,
  COMMAND_STARTED,
  COMMAND_SUCCEEDED,
  CommandFailedEvent,
  CommandStartedEvent,
  CommandSucceededEvent,
  compareObjectId,
  compress,
  Compressor,
  CONNECTION_CHECK_OUT_FAILED,
  CONNECTION_CHECK_OUT_STARTED,
  CONNECTION_CHECKED_IN,
  CONNECTION_CHECKED_OUT,
  CONNECTION_CLOSED,
  CONNECTION_CREATED,
  CONNECTION_POOL_CLEARED,
  CONNECTION_POOL_CLOSED,
  CONNECTION_POOL_CREATED,
  CONNECTION_POOL_READY,
  CONNECTION_READY,
  COSMOS_DB_MSG,
  createStdioLogger,
  CSOTTimeoutContext,
  Db,
  decorateWithExplain,
  DEFAULT_ALLOWED_HOSTS,
  DEFAULT_MAX_DOCUMENT_LENGTH,
  DeprioritizedServers,
  DOCUMENT_DB_MSG,
  Double,
  Explain,
  ExplainVerbosity,
  filterOutOptions,
  FindCursor,
  hasAtomicOperators,
  HostAddress,
  hostMatchesWildcards,
  isHello,
  isResumableError,
  isRetryableReadError,
  isStateChangeError,
  isUint8Array,
  LEGACY_HELLO_COMMAND,
  LEGACY_NOT_PRIMARY_OR_SECONDARY_ERROR_MESSAGE,
  LEGACY_NOT_WRITABLE_PRIMARY_ERROR_MESSAGE,
  LegacyTimeoutContext,
  List,
  Long,
  MongoAPIError,
  MongoBulkWriteError,
  MongoClient,
  MongoCredentials,
  MONGODB_ERROR_CODES,
  MongoDBCollectionNamespace,
  MongoDBNamespace,
  MongoDriverError,
  MongoError,
  MongoErrorLabel,
  MongoInvalidArgumentError,
  MongoLoggableComponent,
  MongoLogger,
  MongoMissingDependencyError,
  MongoNetworkError,
  MongoNetworkTimeoutError,
  MongoOperationTimeoutError,
  MongoParseError,
  MongoRuntimeError,
  MongoServerError,
  MongoSystemError,
  MongoWriteConcernError,
  needsRetryableWriteLabel,
  NODE_IS_RECOVERING_ERROR_MESSAGE,
  ns,
  ObjectId,
  OP_MSG,
  OP_QUERY,
  OpCompressedRequest,
  OpMsgRequest,
  OpQueryRequest,
  parseOptions,
  parseSeverityFromString,
  PoolClosedError,
  processTimeMS,
  ReadConcern,
  ReadPreference,
  resolveRuntimeAdapters,
  resolveSRVRecord,
  ReturnDocument,
  RunCommandOperation,
  ServerApiVersion,
  ServerSession,
  ServerSessionPool,
  setDifference,
  SeverityLevel,
  shuffle,
  SrvPoller,
  StateMachine,
  stringifyWithMaxLen,
  Timeout,
  TimeoutContext,
  TimeoutError,
  Topology,
  TopologyType,
  Transaction,
  uncompressibleCommands,
  WaitQueueTimeoutError,
  WriteConcern,

  AggregateOperation,
  CountOperation,
  CreateCollectionOperation,
  CreateIndexesOperation,
  CreateSearchIndexesOperation,
  DbStatsOperation,
  DeleteManyOperation,
  DeleteOneOperation,
  DeleteOperation,
  DistinctOperation,
  DropCollectionOperation,
  DropDatabaseOperation,
  DropIndexOperation,
  DropSearchIndexOperation,
  EstimatedDocumentCountOperation,
  FindAndModifyOperation,
  FindOneAndDeleteOperation,
  FindOneAndReplaceOperation,
  FindOneAndUpdateOperation,
  FindOperation,
  GetMoreOperation,
  InsertOneOperation,
  InsertOperation,
  KillCursorsOperation,
  ListCollectionsOperation,
  ListDatabasesOperation,
  ListIndexesOperation,
  ProfilingLevelOperation,
  RemoveUserOperation,
  RenameOperation,
  ReplaceOneOperation,
  UpdateManyOperation,
  UpdateOneOperation,
  UpdateOperation,
  UpdateSearchIndexOperation,
  ValidateCollectionOperation,
  SetProfilingLevelOperation,
  MongoBatchReExecutionError,
  MongoClientBulkWriteError,
  CursorTimeoutContext,
  MongoCursorExhaustedError,
  promiseWithResolvers,
  Code,
  CursorResponse,
  Binary,
  BSONSymbol,
  DBRef,
  MaxKey,
  MinKey,
  noop,
  Timestamp,
  formatSort,
  MongoClientClosedError,
  ServerType,
  ScramSHA256,
  AWSSDKCredentialProvider,
  MongoAWSError,
  MongoDBAWS,
  MongoMissingCredentialsError,
  refreshKMSCredentials,
  Decimal128,
  ClientEncryption,
  BSON,
  fetchAzureKMSToken,
  MongoCryptAzureKMSRequestError,
  MongoCryptCreateEncryptedCollectionError,
  MongoCryptError,
  Int32,
  MongoServerSelectionError,
  MongoCryptCreateDataKeyError,
  resolveTimeoutOptions,
  GridFSBucket,
  squashError,
  CursorTimeoutMode,
  BSONType,
  MongoNotConnectedError,
  ProfilingLevel,
  MongoCryptInvalidArgumentError,
  EJSON,
  ServerDescription,
  enumToString,
  BSONRegExp,
  BSONError,
  deserialize,
  OpMsgResponse,
  ReadConcernLevel,
  PoolClearedError,
  SERVER_HEARTBEAT_FAILED,
  SERVER_HEARTBEAT_SUCCEEDED,
  getTopology,
  connect,
  makeClientMetadata,
  MongoClientAuthProviders,
  MongoDBResponse,
  ServerHeartbeatStartedEvent,
  Connection
} = exportSource;

// Export types from the contextified module
export type {
  AbstractCursor,
  AbstractOperation,
  Admin,
  AnyClientBulkWriteModel,
  AWSCredentials,
  ChangeStream,
  ChangeStreamDocument,
  ChangeStreamOptions,
  ClientBulkWriteModel,
  CollectionInfo,
  CommandOptions,
  CompressorName,
  ConnectionCheckOutFailedEvent,
  ConnectionCreatedEvent,
  ConnectionOptions,
  ConnectionPool,
  ConnectionPoolClearedEvent,
  ConnectOptions,
  DataKey,
  DbOptions,
  Document,
  KMSProviders,
  Log,
  MongoChangeStreamError,
  MongoClientOptions,
  MongoDBLogWritable,
  MongoDBResponseConstructor,
  MongoLoggerOptions,
  MongoOptions,
  ResumeToken,
  Runtime,
  Server,
  ServerApi,
  ServerHeartbeatSucceededEvent,
  TopologyDescription,
  TopologyOptions,
  UUID,
  WithId,
  WriteConcernSettings
} from './tools/runner/bundle/types/index';

// Export "clashing" types from the contextified module.
// These are types that clash with the objects of the same name (eg Collection), so we need to export them separately to avoid type errors.
import type {
  AuthMechanism as _AuthMechanism,
  Collection as _Collection,
  CommandFailedEvent as _CommandFailedEvent,
  CommandStartedEvent as _CommandStartedEvent,
  CommandSucceededEvent as _CommandSucceededEvent,
  Connection as _Connection,
  CSOTTimeoutContext as _CSOTTimeoutContext,
  Db as _Db,
  HostAddress as _HostAddress,
  MongoClient as _MongoClient,
  Timeout as _Timeout,
  Topology as _Topology,
  TopologyType as _TopologyType
} from './tools/runner/bundle/types/index';
export type AuthMechanism = _AuthMechanism;
export type Collection = _Collection;
export type Connection = _Connection;
export type CommandFailedEvent = _CommandFailedEvent;
export type CommandStartedEvent = _CommandStartedEvent;
export type CommandSucceededEvent = _CommandSucceededEvent;
export type CSOTTimeoutContext = _CSOTTimeoutContext;
export type Db = _Db;
export type HostAddress = _HostAddress;
export type MongoClient = _MongoClient;
export type Timeout = _Timeout;
export type Topology = _Topology;
export type TopologyType = _TopologyType;

// Export specific types from other files in the contextified module
export type { AzureKMSRequestOptions } from './tools/runner/bundle/types/client-side-encryption/providers/azure';
export type { AwsSigv4Options } from './tools/runner/bundle/types/cmap/auth/aws4';
export type {
  MongoDBOIDC,
  OIDCCallbackFunction,
  OIDCCallbackParams,
  OIDCResponse
} from './tools/runner/bundle/types/cmap/auth/mongodb_oidc';
