import { loadContextifiedMongoDBModule } from './tools/runner/vm_context_helper';

type all = typeof import('./mongodb');
let exportSource: all;
try {
  exportSource = loadContextifiedMongoDBModule() as all;
} catch (error) {
  throw new Error(
    `Failed to load contextified MongoDB module: ${error instanceof Error ? error.message : String(error)}`
  );
}

// Export public API from the contextified module
// Hint: This list isn't automatically alphabetized, but VSCode's "Sort Lines Ascending" command can be used to keep it organized
export const {
  abortable,
  AbstractCursor,
  AggregateOperation,
  AggregationCursor,
  applySession,
  AUTH_MECHS_AUTH_SRC_EXTERNAL,
  AuthMechanism,
  aws4Sign,
  AWSSDKCredentialProvider,
  Binary,
  BSON,
  BSONError,
  BSONRegExp,
  BSONSymbol,
  BSONType,
  BufferPool,
  ChangeStream,
  ChangeStreamCursor,
  checkParentDomainMatch,
  ClientEncryption,
  ClientSession,
  CMAP_EVENTS,
  Code,
  Collection,
  COMMAND_FAILED,
  COMMAND_STARTED,
  COMMAND_SUCCEEDED,
  CommandFailedEvent,
  CommandStartedEvent,
  CommandSucceededEvent,
  compareObjectId,
  compress,
  Compressor,
  connect,
  CONNECTION_CHECK_OUT_FAILED,
  CONNECTION_CHECK_OUT_STARTED,
  CONNECTION_CHECKED_IN,
  CONNECTION_CHECKED_OUT,
  CONNECTION_CLOSED,
  CONNECTION_CREATED,
  CONNECTION_POOL_CLEARED,
  CONNECTION_POOL_CLOSED,
  CONNECTION_POOL_CREATED,
  CONNECTION_POOL_READY,
  CONNECTION_READY,
  Connection,
  ConnectionCheckedInEvent,
  ConnectionCheckedOutEvent,
  ConnectionCheckOutFailedEvent,
  ConnectionCheckOutStartedEvent,
  ConnectionClosedEvent,
  ConnectionCreatedEvent,
  ConnectionPool,
  ConnectionPoolClearedEvent,
  ConnectionPoolClosedEvent,
  ConnectionPoolCreatedEvent,
  ConnectionPoolReadyEvent,
  ConnectionReadyEvent,
  COSMOS_DB_MSG,
  CountOperation,
  CreateCollectionOperation,
  CreateIndexesOperation,
  CreateSearchIndexesOperation,
  createStdioLogger,
  CSOTTimeoutContext,
  CursorResponse,
  CursorTimeoutContext,
  CursorTimeoutMode,
  Db,
  DBRef,
  DbStatsOperation,
  Decimal128,
  decorateWithExplain,
  DEFAULT_ALLOWED_HOSTS,
  DEFAULT_MAX_DOCUMENT_LENGTH,
  DeleteManyOperation,
  DeleteOneOperation,
  DeleteOperation,
  DeprioritizedServers,
  deserialize,
  DistinctOperation,
  DOCUMENT_DB_MSG,
  Double,
  DropCollectionOperation,
  DropDatabaseOperation,
  DropIndexOperation,
  DropSearchIndexOperation,
  EJSON,
  enumToString,
  EstimatedDocumentCountOperation,
  Explain,
  ExplainVerbosity,
  fetchAzureKMSToken,
  filterOutOptions,
  FindAndModifyOperation,
  FindCursor,
  FindOneAndDeleteOperation,
  FindOneAndReplaceOperation,
  FindOneAndUpdateOperation,
  FindOperation,
  formatSort,
  getFAASEnv,
  getMongoDBClientEncryption,
  GetMoreOperation,
  getTopology,
  GridFSBucket,
  hasAtomicOperators,
  HEARTBEAT_EVENTS,
  HostAddress,
  hostMatchesWildcards,
  InsertOneOperation,
  InsertOperation,
  Int32,
  isDriverInfoEqual,
  isHello,
  isResumableError,
  isRetryableReadError,
  isStateChangeError,
  isUint8Array,
  KillCursorsOperation,
  LEGACY_HELLO_COMMAND,
  LEGACY_NOT_PRIMARY_OR_SECONDARY_ERROR_MESSAGE,
  LEGACY_NOT_WRITABLE_PRIMARY_ERROR_MESSAGE,
  LegacyTimeoutContext,
  List,
  ListCollectionsCursor,
  ListCollectionsOperation,
  ListDatabasesOperation,
  ListIndexesOperation,
  Long,
  makeClientMetadata,
  MaxKey,
  MinKey,
  MongoAPIError,
  MongoAWSError,
  MongoBatchReExecutionError,
  MongoBulkWriteError,
  MongoClient,
  MongoClientAuthProviders,
  MongoClientBulkWriteError,
  MongoClientClosedError,
  MongoCredentials,
  MongoCryptAzureKMSRequestError,
  MongoCryptCreateDataKeyError,
  MongoCryptCreateEncryptedCollectionError,
  MongoCryptError,
  MongoCryptInvalidArgumentError,
  MongoCursorExhaustedError,
  MONGODB_ERROR_CODES,
  MongoDBAWS,
  MongoDBCollectionNamespace,
  MongoDBNamespace,
  MongoDBResponse,
  MongoDriverError,
  MongoError,
  MongoErrorLabel,
  MongoInvalidArgumentError,
  MongoLoggableComponent,
  MongoLogger,
  MongoMissingCredentialsError,
  MongoMissingDependencyError,
  MongoNetworkError,
  MongoNetworkTimeoutError,
  MongoNotConnectedError,
  MongoOperationTimeoutError,
  MongoParseError,
  MongoRuntimeError,
  MongoServerError,
  MongoServerSelectionError,
  MongoSystemError,
  MongoWriteConcernError,
  needsRetryableWriteLabel,
  NODE_IS_RECOVERING_ERROR_MESSAGE,
  noop,
  ns,
  ObjectId,
  OP_MSG,
  OP_QUERY,
  OpCompressedRequest,
  OpMsgRequest,
  OpMsgResponse,
  OpQueryRequest,
  parseOptions,
  parseSeverityFromString,
  PoolClearedError,
  PoolClosedError,
  processTimeMS,
  ProfilingLevel,
  ProfilingLevelOperation,
  promiseWithResolvers,
  ReadConcern,
  ReadConcernLevel,
  ReadPreference,
  refreshKMSCredentials,
  RemoveUserOperation,
  RenameOperation,
  ReplaceOneOperation,
  resolveRuntimeAdapters,
  resolveSRVRecord,
  resolveTimeoutOptions,
  ReturnDocument,
  RunCommandOperation,
  ScramSHA256,
  SENSITIVE_COMMANDS,
  SERVER_DESCRIPTION_CHANGED,
  SERVER_HEARTBEAT_FAILED,
  SERVER_HEARTBEAT_SUCCEEDED,
  Server,
  ServerApiVersion,
  ServerClosedEvent,
  ServerDescription,
  ServerDescriptionChangedEvent,
  ServerHeartbeatFailedEvent,
  ServerHeartbeatStartedEvent,
  ServerHeartbeatSucceededEvent,
  ServerOpeningEvent,
  ServerSession,
  ServerSessionPool,
  ServerType,
  setDifference,
  SetProfilingLevelOperation,
  SeverityLevel,
  shuffle,
  squashError,
  SrvPoller,
  StateMachine,
  stringifyWithMaxLen,
  Timeout,
  TimeoutContext,
  TimeoutError,
  Timestamp,
  TOPOLOGY_EVENTS,
  Topology,
  TopologyClosedEvent,
  TopologyDescriptionChangedEvent,
  TopologyOpeningEvent,
  TopologyType,
  Transaction,
  uncompressibleCommands,
  UpdateManyOperation,
  UpdateOneOperation,
  UpdateOperation,
  UpdateSearchIndexOperation,
  UUID,
  ValidateCollectionOperation,
  WaitQueueTimeoutError,
  WriteConcern
} = exportSource;

// Export types from the contextified module
export type {
  AbstractOperation,
  Admin,
  AnyClientBulkWriteModel,
  AutoEncrypter,
  AutoEncryptionOptions,
  AWSCredentials,
  BSONSerializeOptions,
  BSONTypeAlias,
  ChangeStreamCollModDocument,
  ChangeStreamCreateDocument,
  ChangeStreamCreateIndexDocument,
  ChangeStreamDeleteDocument,
  ChangeStreamDocument,
  ChangeStreamDocumentCommon,
  ChangeStreamDocumentKey,
  ChangeStreamDropDatabaseDocument,
  ChangeStreamDropDocument,
  ChangeStreamDropIndexDocument,
  ChangeStreamInsertDocument,
  ChangeStreamInvalidateDocument,
  ChangeStreamNameSpace,
  ChangeStreamOptions,
  ChangeStreamRefineCollectionShardKeyDocument,
  ChangeStreamRenameDocument,
  ChangeStreamReplaceDocument,
  ChangeStreamReshardCollectionDocument,
  ChangeStreamShardCollectionDocument,
  ChangeStreamUpdateDocument,
  ClientBulkWriteModel,
  ClientDeleteManyModel,
  ClientDeleteOneModel,
  ClientEncryptionDataKeyProvider,
  ClientInsertOneModel,
  ClientMetadata,
  ClientReplaceOneModel,
  ClientUpdateManyModel,
  ClientUpdateOneModel,
  ClusterTime,
  CollectionInfo,
  CollectionOptions,
  CommandOptions,
  CompressorName,
  ConnectionOptions,
  ConnectionPoolOptions,
  ConnectOptions,
  DataKey,
  DbOptions,
  Document,
  DriverInfo,
  Filter,
  InferIdType,
  KMSProviders,
  Log,
  MongoChangeStreamError,
  MongoClientOptions,
  MongoDBLogWritable,
  MongoDBResponseConstructor,
  MongoLoggerOptions,
  MongoOptions,
  OneOrMore,
  OptionalId,
  ReadPreferenceMode,
  ResumeToken,
  Runtime,
  ServerApi,
  ServerSessionId,
  TagSet,
  TopologyDescription,
  TopologyOptions,
  TransactionOptions,
  UpdateDescription,
  UpdateFilter,
  W,
  WithId,
  WithoutId,
  WriteConcernSettings
} from './tools/runner/bundle/types/index';

// Export "clashing" types from the contextified module.
// These are types that clash with the objects of the same name (eg Collection), so we need to export them separately to avoid type errors.
import type {
  AbstractCursor as _AbstractCursor,
  AuthMechanism as _AuthMechanism,
  ChangeStream as _ChangeStream,
  ClientEncryption as _ClientEncryption,
  ClientSession as _ClientSession,
  Collection as _Collection,
  CommandFailedEvent as _CommandFailedEvent,
  CommandStartedEvent as _CommandStartedEvent,
  CommandSucceededEvent as _CommandSucceededEvent,
  Connection as _Connection,
  ConnectionClosedEvent as _ConnectionClosedEvent,
  ConnectionPool as _ConnectionPool,
  ConnectionPoolClearedEvent as _ConnectionPoolClearedEvent,
  CSOTTimeoutContext as _CSOTTimeoutContext,
  CursorTimeoutContext as _CursorTimeoutContext,
  Db as _Db,
  FindCursor as _FindCursor,
  GridFSBucket as _GridFSBucket,
  HostAddress as _HostAddress,
  MongoClient as _MongoClient,
  MongoError as _MongoError,
  Server as _Server,
  ServerDescriptionChangedEvent as _ServerDescriptionChangedEvent,
  Timeout as _Timeout,
  TimeoutContext as _TimeoutContext,
  Topology as _Topology,
  TopologyDescriptionChangedEvent as _TopologyDescriptionChangedEvent,
  TopologyType as _TopologyType,
  UUID as _UUID
} from './tools/runner/bundle/types/index';
export type AbstractCursor = _AbstractCursor;
export type AuthMechanism = _AuthMechanism;
export type ChangeStream = _ChangeStream;
export type ClientEncryption = _ClientEncryption;
export type ClientSession = _ClientSession;
export type Collection = _Collection;
export type CommandFailedEvent = _CommandFailedEvent;
export type CommandStartedEvent = _CommandStartedEvent;
export type CommandSucceededEvent = _CommandSucceededEvent;
export type Connection = _Connection;
export type ConnectionClosedEvent = _ConnectionClosedEvent;
export type ConnectionPool = _ConnectionPool;
export type ConnectionPoolClearedEvent = _ConnectionPoolClearedEvent;
export type CSOTTimeoutContext = _CSOTTimeoutContext;
export type CursorTimeoutContext = _CursorTimeoutContext;
export type Db = _Db;
export type FindCursor = _FindCursor;
export type GridFSBucket = _GridFSBucket;
export type HostAddress = _HostAddress;
export type MongoClient = _MongoClient;
export type MongoError = _MongoError;
export type Server = _Server;
export type ServerDescriptionChangedEvent = _ServerDescriptionChangedEvent;
export type Timeout = _Timeout;
export type TimeoutContext = _TimeoutContext;
export type Topology = _Topology;
export type TopologyDescriptionChangedEvent = _TopologyDescriptionChangedEvent;
export type TopologyType = _TopologyType;
export type UUID = _UUID;

// Export specific types from other files in the contextified module
export type { AzureKMSRequestOptions } from './tools/runner/bundle/types/client-side-encryption/providers/azure';
export type { AwsSigv4Options } from './tools/runner/bundle/types/cmap/auth/aws4';
export type {
  MongoDBOIDC,
  OIDCCallbackFunction,
  OIDCCallbackParams,
  OIDCResponse
} from './tools/runner/bundle/types/cmap/auth/mongodb_oidc';
