name: Compress and Sign
description: 'Compresses package and signs with garasign'

inputs: 
    garasign_username:
      description: 'Garasign username input for drivers-github-tools/garasign/gpg-sign'
      required: true
    garasign_password:
      description: 'Garasign password input for drivers-github-tools/garasign/gpg-sign'
      required: true
    artifactory_username:
      description: 'Artifactory username input for drivers-github-tools/garasign/gpg-sign'
      required: true
    artifactory_password:
      description: 'Artifactory password input for drivers-github-tools/garasign/gpg-sign'
      required: true

runs:
  using: composite
  steps:
    - run: npm pack
      shell: bash

    - name: Get release version and release package file name
      id: get_vars
      shell: bash
      run: |
        package_version=$(jq --raw-output '.version' package.json)
        echo "package_version=${package_version}" >> "$GITHUB_OUTPUT"
        echo "package_file=mongodb-${package_version}.tgz" >> "$GITHUB_OUTPUT"
    - name: Create detached signature
      uses: mongodb-labs/drivers-github-tools/garasign/gpg-sign@v1
      with:
        filenames: ${{ steps.get_vars.outputs.package_file }}
        garasign_username: ${{ inputs.garasign_username }}
        garasign_password: ${{ inputs.garasign_password }}
        artifactory_username: ${{ inputs.artifactory_username }}
        artifactory_password: ${{ inputs.artifactory_password }}

    - name: "Upload release artifacts"
      run: gh release upload v${{ steps.get_vars.outputs.package_version }} ${{ steps.get_vars.outputs.package_file }}.sig
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}