#! /usr/bin/env bash

export MONGODB_VERSION=${VERSION}
echo  "MONGODB_VERSION=${VERSION}"

export TOPOLOGY=${TOPOLOGY}
echo  "TOPOLOGY=${TOPOLOGY}"

export AUTH=${AUTH}
echo  "AUTH=${AUTH}"

export SSL=${SSL}
echo  "SSL=${SSL}"

export ORCHESTRATION_FILE=${ORCHESTRATION_FILE}
echo  "ORCHESTRATION_FILE=${ORCHESTRATION_FILE}"

export REQUIRE_API_VERSION=${REQUIRE_API_VERSION}
echo  "REQUIRE_API_VERSION=${REQUIRE_API_VERSION}"

export LOAD_BALANCER=${LOAD_BALANCER}
echo  "LOAD_BALANCER=${LOAD_BALANCER}"

export COMPRESSOR=${COMPRESSOR}
echo  "COMPRESSOR=${COMPRESSOR}"

bash "${DRIVERS_TOOLS}/.evergreen/run-orchestration.sh"
