#!/bin/bash
set -o errexit  # Exit the script with error if any of the commands fail

# export DRIVERS_ATLAS_PUBLIC_API_KEY=${DRIVERS_ATLAS_PUBLIC_API_KEY}
# export DRIVERS_ATLAS_PRIVATE_API_KEY=${DRIVERS_ATLAS_PRIVATE_API_KEY}
# export DRIVERS_ATLAS_LAMBDA_USER=${DRIVERS_ATLAS_LAMBDA_USER}
# export DRIVERS_ATLAS_LAMBDA_PASSWORD=${DRIVERS_ATLAS_LAMBDA_PASSWORD}
# export DRIVERS_ATLAS_GROUP_ID=${DRIVERS_ATLAS_GROUP_ID}
# export TEST_LAMBDA_DIRECTORY=${TEST_LAMBDA_DIRECTORY}
# export LAMBDA_STACK_NAME=${LAMBDA_STACK_NAME}

. ${DRIVERS_TOOLS}/.evergreen/run-deployed-lambda-aws-tests.sh
