var shared = require('./shared');
shared.object = { name: 1, age: -1 };
shared.array = ['name']
shared.string = 'woot'
shared.string2 = String('woot')
shared.number = 3
shared.number2 = Number(3)
shared.bool = true
shared.bool2 = Boolean(true)
shared.date = new Date;