name: Setup
description: 'Installs node, driver dependencies, and builds source'

steps:
  - uses: actions/setup-node@v3
    with:
      node-version: 'lts/*'
      cache: 'npm'
      registry-url: 'https://registry.npmjs.org'
  - run: npm install -g npm@latest
  - run: npm clean-install
