baseurl = "/mongo-nodejs-driver/"
languageCode = "en-us"
title = "MongoDB Node.js Driver"
canonifyurls = false

githubRepo = "node-mongodb-native"

[params]
    referenceDocsUrl = "https://www.mongodb.com/docs/drivers/node"
