graph TD
  MongoRuntimeError --> MongoTransactionError
  MongoRuntimeError --> MongoExpiredSessionError
  MongoRuntimeError --> MongoKerberosError
  MongoRuntimeError --> MongoResourceClosedError

  MongoResourceClosedError --> MongoServerClosedError
  MongoResourceClosedError --> MongoStreamClosedError
  MongoResourceClosedError --> MongoTopologyClosedError
