graph TD
    MongoAPIError --> MongoTailableCursorError
    MongoAPIError --> MongoCursorExhaustedError
    MongoAPIError --> MongoCursorInUseError
    MongoAPIError --> MongoServerClosedError
    MongoAPIError --> MongoTopologyClosedError
    MongoAPIError --> MongoNotConnectedError
