graph TD
    MongoError --> MongoDriverError
    MongoError --> MongoNetworkError
    MongoError --> MongoServerError
    MongoError --> MongoSystemError
    MongoDriverError --> MongoLogicError
    MongoDriverError --> MongoRuntimeError
    
