graph TD
  MongoRuntimeError --> MongoClientNotConnectedError
  MongoRuntimeError --> MongoTransactionError
  MongoRuntimeError --> MongoExpiredSessionError
  MongoRuntimeError --> MongoKerberosClientConnectionError
  MongoRuntimeError --> MongoInternalDriverError
  MongoRuntimeError --> MongoDecompressionError
  MongoRuntimeError --> MongoCompressionError
  MongoRuntimeError --> MongoEncryptionError
  MongoRuntimeError --> MongoParseError
  MongoRuntimeError --> MongoIOError
  MongoRuntimeError --> MongoServerSelectionError
