graph TD
    MongoAPIError --> MongoInvalidArgumentError
    MongoAPIError --> MongoCompatibilityError
    MongoAPIError --> MongoMissingCredentialsError
    MongoAPIError --> MongoMissingDependencyError
