graph TD
  MongoRuntimeError --> MongoEncryptionError
  MongoRuntimeError --> MongoURIError
  MongoRuntimeError --> MongoIOError
  MongoRuntimeError --> MongoServerSelectionError
  MongoRuntimeError --> MongoStreamError

  MongoStreamError --> MongoChangeStreamError
  MongoStreamError --> MongoGridFSStreamError

  MongoGridFSStreamError --> MongoGridFSChunkError
