graph TD
  MongoRuntimeError --> MongoBatchError
  MongoRuntimeError --> MongoCursorError
  MongoRuntimeError --> MongoUnsupportedOperationError
  MongoRuntimeError --> MongoDecompressionError
  MongoRuntimeError --> MongoCompressionError
  MongoRuntimeError --> MongoInvalidClassInstantiationError

  MongoBatchError --> MongoBatchReExecutionError

  MongoCursorError --> MongoCursorExhaustedError

  MongoUnsupportedOperationError --> MongoInvalidCursorOperationError
