graph TD
  MongoRuntimeError --> MongoCompressionError
  MongoRuntimeError --> MongoDecompressionError
  MongoRuntimeError --> MongoGridFSChunkError
  MongoRuntimeError --> MongoGridFSStreamError
  MongoRuntimeError --> MongoChangeStreamError
