graph TD
  MongoRuntimeError --> MongoTransactionError
  MongoRuntimeError --> MongoExpiredSessionError
  MongoRuntimeError --> MongoKerberosError
  MongoRuntimeError --> MongoResourceClosedError
  MongoRuntimeError --> MongoInvalidClassInstantiationError

  MongoResourceClosedError --> MongoServerClosedError
  MongoResourceClosedError --> MongoStreamClosedError
  MongoResourceClosedError --> MongoTopologyClosedError
