graph TD
    MongoRuntimeError --> MongoResourceClosedError
    MongoBatchError --> MongoBatchReExecutionError
    MongoRuntimeError --> MongoBatchError
    MongoRuntimeError --> MongoCursorError
    MongoRuntimeError --> MongoUnsupportedOperationError
    MongoUnsupportedOperationError --> MongoInvalidCursorOperationError
    MongoRuntimeError --> MongoClientNotConnectedError
    MongoRuntimeError --> MongoTransactionError
    MongoRuntimeError --> MongoExpiredSessionError
    MongoResourceClosedError --> MongoServerClosedError
    MongoRuntimeError --> MongoKerberosClientConnectionError
    MongoRuntimeError --> MongoInternalDriverError
    MongoRuntimeError --> MongoStreamError
    MongoStreamError --> MongoChangeStreamError
    MongoStreamError --> MongoGridFSStreamError
    MongoGridFSStreamError --> MongoGridFSChunkError
    MongoResourceClosedError --> MongoStreamClosedError
    MongoChangeStreamError --> MongoNoResumeTokenInChangeStreamError
    MongoChangeStreamError --> MongoNoCursorInChangeStreamError
    MongoRuntimeError --> MongoDecompressionError
    MongoRuntimeError --> MongoCompressionError
    MongoRuntimeError --> MongoEncryptionError
    MongoRuntimeError --> MongoParseError
    MongoCursorError --> MongoCursorExhaustedError
    MongoResourceClosedError --> MongoTopologyClosedError
    MongoRuntimeError --> MongoIOError
    MongoRuntimeError --> MongoServerSelectionError