graph TD
  MongoRuntimeError --> MongoEncryptionError
  MongoRuntimeError --> MongoParseError
  MongoRuntimeError --> MongoIOError
  MongoRuntimeError --> MongoServerSelectionError
  MongoRuntimeError --> MongoStreamError

  MongoStreamError --> MongoChangeStreamError
  MongoStreamError --> MongoGridFSStreamError

  MongoChangeStreamError --> MongoNoResumeTokenInChangeStreamError
  MongoChangeStreamError --> MongoNoCursorInChangeStreamError
  MongoGridFSStreamError --> MongoGridFSChunkError
