graph TD
    MongoLogicError --> MongoInvalidArgumentError
    MongoLogicError --> MongoCompatibilityError
    MongoLogicError --> MongoClientInstantiationError
    MongoLogicError --> MongoMissingCredentialsError
    MongoLogicError --> MongoMissingDependencyError
