graph TD
  MongoRuntimeError --> MongoBatchError
  MongoRuntimeError --> MongoCursorError
  MongoRuntimeError --> MongoUnsupportedOperationError
  MongoRuntimeError --> MongoDecompressionError
  MongoRuntimeError --> MongoCompressionError

  MongoBatchError --> MongoBatchReExecutionError

  MongoCursorError --> MongoCursorExhaustedError

  MongoUnsupportedOperationError --> MongoInvalidCursorOperationError
