const SYSTEM_NAMESPACE_COLLECTION = 'system.namespaces';
const SYSTEM_INDEX_COLLECTION = 'system.indexes';
const SYSTEM_PROFILE_COLLECTION = 'system.profile';
const SYSTEM_USER_COLLECTION = 'system.users';
const SYSTEM_COMMAND_COLLECTION = '$cmd';
const SYSTEM_JS_COLLECTION = 'system.js';

export {
  SYSTEM_NAMESPACE_COLLECTION,
  SYSTEM_INDEX_COLLECTION,
  SYSTEM_PROFILE_COLLECTION,
  SYSTEM_USER_COLLECTION,
  SYSTEM_COMMAND_COLLECTION,
  SYSTEM_JS_COLLECTION
};
