import { expect } from 'chai';

// Exception to the import from mongodb rule we're unit testing our public API
// eslint-disable-next-line @typescript-eslint/no-restricted-imports
import * as mongodb from '../../src/index';
import { setDifference } from '../mongodb';

const EXPECTED_EXPORTS = [
  'AbstractCursor',
  'Admin',
  'AggregationCursor',
  'AuthMechanism',
  'AutoEncryptionLoggerLevel',
  'BatchType',
  'Binary',
  'BSON',
  'BSONRegExp',
  'BSONSymbol',
  'BSONType',
  'CancellationToken',
  'ChangeStream',
  'ChangeStreamCursor',
  'ClientEncryption',
  'ClientSession',
  'Code',
  'Collection',
  'CommandFailedEvent',
  'CommandStartedEvent',
  'CommandSucceededEvent',
  'Compressor',
  'configureExplicitResourceManagement',
  'ConnectionCheckedInEvent',
  'ConnectionCheckedOutEvent',
  'ConnectionCheckOutFailedEvent',
  'ConnectionCheckOutStartedEvent',
  'ConnectionClosedEvent',
  'ConnectionCreatedEvent',
  'ConnectionPoolClearedEvent',
  'ConnectionPoolClosedEvent',
  'ConnectionPoolCreatedEvent',
  'ConnectionPoolMonitoringEvent',
  'ConnectionPoolReadyEvent',
  'ConnectionReadyEvent',
  'CURSOR_FLAGS',
  'CursorTimeoutMode',
  'Db',
  'DBRef',
  'Decimal128',
  'Double',
  'ExplainableCursor',
  'ExplainVerbosity',
  'FindCursor',
  'GridFSBucket',
  'GridFSBucketReadStream',
  'GridFSBucketWriteStream',
  'GSSAPICanonicalizationValue',
  'Int32',
  'ListCollectionsCursor',
  'ListIndexesCursor',
  'Long',
  'MaxKey',
  'MinKey',
  'MongoAPIError',
  'MongoAWSError',
  'MongoAzureError',
  'MongoBatchReExecutionError',
  'MongoBulkWriteError',
  'MongoChangeStreamError',
  'MongoClient',
  'MongoClientAuthProviders',
  'MongoClientBulkWriteCursorError',
  'MongoClientBulkWriteError',
  'MongoClientBulkWriteExecutionError',
  'MongoClientClosedError',
  'MongoCompatibilityError',
  'MongoCryptAzureKMSRequestError',
  'MongoCryptCreateDataKeyError',
  'MongoCryptCreateEncryptedCollectionError',
  'MongoCryptError',
  'MongoCryptInvalidArgumentError',
  'MongoCryptKMSRequestNetworkTimeoutError',
  'MongoCursorExhaustedError',
  'MongoCursorInUseError',
  'MongoDecompressionError',
  'MongoDriverError',
  'MongoError',
  'MongoErrorLabel',
  'MongoExpiredSessionError',
  'MongoGCPError',
  'MongoGridFSChunkError',
  'MongoGridFSStreamError',
  'MongoInvalidArgumentError',
  'MongoKerberosError',
  'MongoLoggableComponent',
  'MongoMissingCredentialsError',
  'MongoMissingDependencyError',
  'MongoNetworkError',
  'MongoNetworkTimeoutError',
  'MongoNotConnectedError',
  'MongoOIDCError',
  'MongoOperationTimeoutError',
  'MongoParseError',
  'MongoRuntimeError',
  'MongoServerClosedError',
  'MongoServerError',
  'MongoServerSelectionError',
  'MongoStalePrimaryError',
  'MongoSystemError',
  'MongoTailableCursorError',
  'MongoTopologyClosedError',
  'MongoTransactionError',
  'MongoUnexpectedServerResponseError',
  'MongoWriteConcernError',
  'ObjectId',
  'OrderedBulkOperation',
  'ProfilingLevel',
  'ReadConcern',
  'ReadConcernLevel',
  'ReadPreference',
  'ReadPreferenceMode',
  'ReturnDocument',
  'ServerApiVersion',
  'ServerClosedEvent',
  'ServerDescriptionChangedEvent',
  'ServerHeartbeatFailedEvent',
  'ServerHeartbeatStartedEvent',
  'ServerHeartbeatSucceededEvent',
  'ServerOpeningEvent',
  'ServerSelectionEvent',
  'ServerSelectionFailedEvent',
  'ServerSelectionStartedEvent',
  'ServerSelectionSucceededEvent',
  'ServerType',
  'SeverityLevel',
  'SrvPollingEvent',
  'Timestamp',
  'TopologyClosedEvent',
  'TopologyDescriptionChangedEvent',
  'TopologyOpeningEvent',
  'TopologyType',
  'UnorderedBulkOperation',
  'UUID',
  'WaitingForSuitableServerEvent',
  'WriteConcern',
  'WriteConcernErrorResult'
];

describe('mongodb entrypoint', () => {
  it('exports all the expected keys', () => {
    expect(setDifference(EXPECTED_EXPORTS, Object.keys(mongodb))).to.be.empty;
  });

  it('exports only the expected keys', () => {
    expect(setDifference(Object.keys(mongodb), EXPECTED_EXPORTS)).to.be.empty;
  });
});
