'use strict';
const MIN_SUPPORTED_SERVER_VERSION = '2.6';
const MAX_SUPPORTED_SERVER_VERSION = '4.4';
const MIN_SUPPORTED_WIRE_VERSION = 2;
const MAX_SUPPORTED_WIRE_VERSION = 9;
const OP_REPLY = 1;
const OP_UPDATE = 2001;
const OP_INSERT = 2002;
const OP_QUERY = 2004;
const OP_GETMORE = 2005;
const OP_DELETE = 2006;
const OP_KILL_CURSORS = 2007;
const OP_COMPRESSED = 2012;
const OP_MSG = 2013;

export {
  MIN_SUPPORTED_SERVER_VERSION,
  MAX_SUPPORTED_SERVER_VERSION,
  MIN_SUPPORTED_WIRE_VERSION,
  MAX_SUPPORTED_WIRE_VERSION,
  OP_REPLY,
  OP_UPDATE,
  OP_INSERT,
  OP_QUERY,
  OP_GETMORE,
  OP_DELETE,
  OP_KILL_CURSORS,
  OP_COMPRESSED,
  OP_MSG
};
