name: test_admin_list
on: workflow_dispatch

permissions:
    contents: write
    pull-requests: write

jobs:
  print_admins:
    runs-on: ubuntu-latest
    steps:
      - name: check if triggering_actor is allowed to generate notes
        env:
          GITHUB_TOKEN: ${{ github.token }}
          COMMENTER: ${{ github.triggering_actor && github.triggering_actor || 'empty_triggering_actor' }}
          API_ENDPOINT: /repos/${{ github.repository }}/collaborators?permission=admin
        shell: bash
        run: gh api "$API_ENDPOINT" --paginate --jq ".[].login"
