on:
  # Allows us to manually trigger an alpha
  # workflow_dispatch can be given an alternative 'ref' to release from a feature branch
  workflow_dispatch:
    inputs:
      alphaVersion:
        description: 'Enter alpha version'
        required: true
        type: string

name: release-alpha

jobs:
  release-alpha:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - shell: bash
        run: |
          ALPHA_SEMVER_REGEXP="-alpha(\.(0|[1-9][0-9]+))?$"

          if ! [[ "${{ inputs.alphaVersion }}" =~ $ALPHA_SEMVER_REGEXP ]]; then
            echo "Invalid alphaVersion string"
            exit 1
          fi
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup.yml
      - run: npm version "${{ inputs.alphaVersion }}" --git-tag-version=false
      # TODO: Remove dry-run before merging
      - run: npm publish --dry-run --provenance --tag=alpha
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
