on:
  schedule:
    # Timezone is UTC
    # https://crontab.guru/#0_0_*_*_*
    # At 00:00 every day.
    - cron: '0 0 * * *'

  # Allows us to manually trigger a nightly
  # A nightly can be release more than one nightly in a day if the commit from main
  # has changed since
  workflow_dispatch: {}

name: release-nightly

jobs:
  release-nightly:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: NODE-5340
      - uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          registry-url: 'https://registry.npmjs.org'
      - run: npm install -g npm
      - run: npm clean-install
      - id: build_nightly
        run: node ./.github/scripts/nightly.mjs
      - if: ${{ steps.build_nightly.outputs.publish == 'yes' }}
        run: npm publish --provenance --tag=nightly
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
