on:
  # Allows us to manually trigger an alpha
  # workflow_dispatch can be given an alternative 'ref' to release from a feature branch
  workflow_dispatch:
    inputs:
      alphaVersion:
        description: 'Enter alpha version'
        required: true
        type: string

name: release-alpha

jobs:
  release-alpha:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - shell: bash
        run: |
          ALPHA_SEMVER_REGEXP="-alpha(\.(0|[1-9][0-9]+))?$"

          if ! [[ "${{ inputs.alphaVersion }}" =~ $ALPHA_SEMVER_REGEXP ]]; then
            echo "Invalid alphaVersion string"
            exit 1
          fi
      - uses: actions/checkout@v3
      # TODO: replace with setup
      - uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'
      - run: npm install -g npm@latest
      - run: npm clean-install
      - run: npm version "${{ inputs.alphaVersion }}" --git-tag-version=false
      - run: npm publish --provenance --tag=alpha
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
