on:
  push:
    branches: [5.x]
  workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: write
  actions: write

name: release-5x

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - id: release
        uses: google-github-actions/release-please-action@v4
        with:
          target-branch: 5.x

      # If release-please created a release, publish to npm
      - if: ${{ steps.release.outputs.release_created }}
        uses: actions/checkout@v4
      - if: ${{ steps.release.outputs.release_created }}
        name: Dispatch npm-publish workflow
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          node ./.github/scripts/dispatch-and-wait.mjs npm-publish.yml \
            tag=5x \
            version="$(node -p "require('./package.json').version")" \
            ref="${{ github.sha }}"
