on:
  # schedule:
  #   # Timezone is UTC
  #   # https://crontab.guru/#0_0_*_*_*
  #   # At 00:00 every day.
  #   # Every 15 minutes for testing
  #   - cron: '*/15 * * * *'
  pull_request:
    branches: [ main ]

name: release-nightly

jobs:
  release-nightly:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          registry-url: 'https://registry.npmjs.org'
      - run: npm install -g npm
      - run: npm clean-install
      - id: build_nightly
        run: node ./.github/scripts/nightly.mjs
      - if: ${{ steps.build_nightly.outputs.publish == 'yes' }}
        run: npm publish --dry-run --provenance --tag=nightly
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
