on:
  # Allows us to manually trigger an alpha
  # workflow_dispatch can be given an alternative 'ref' to release from a feature branch
  workflow_dispatch:
    inputs:
      alphaVersion:
        description: 'Enter alpha version'
        required: true
        type: string

permissions:
  actions: write
  contents: read

name: release-alpha

jobs:
  release-alpha:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        env:
          ALPHA_VERSION: ${{ inputs.alphaVersion }}
        run: |
          ALPHA_SEMVER_REGEXP="-alpha(\.([0-9]|[1-9][0-9]+))?$"

          if ! [[ "$ALPHA_VERSION" =~ $ALPHA_SEMVER_REGEXP ]]; then
            echo "Invalid alphaVersion string"
            exit 1
          fi
      - uses: actions/checkout@v5
      - name: Dispatch npm-publish workflow
        env:
          GH_TOKEN: ${{ github.token }}
          ALPHA_VERSION: ${{ inputs.alphaVersion }}
        run: |
          node ./.github/scripts/dispatch-and-wait.mjs npm-publish.yml \
            tag=alpha \
            version="$ALPHA_VERSION" \
            ref="${{ github.sha }}"
